### PR TITLE
Refactored user/project settings

### PR DESCRIPTION
**Pull request by jeffcampbellmakesgames**
## Summary
I recently pulled this library as a package into a new project and had a hard time tracking down the settings to disable the debug feature. I realized that some of the existing settings for debugging or gizmos are checked in as part of the Settings scriptable asset which means one developer's preferences could potentially clobber another developer's preferences.

To make it easier to expose these settings to the user in a standard way as well as to separate user preferences off of the checked-in Settings asset, I've created a new preference class that allows easier access for developers to these settings regardless of the Settings asset location and separates the Gizmo/Debug configuration to use Editor Prefs instead. 

A developer can now modify their user preferences at the menu item **Unity=>Preferences** and navigate to the **SOArchitecture** section as shown below. These are now saved as Editor Prefs and can differ per developer.

image

image

A developer can correspondingly modify the project-wide settings by opening the menu item **Edit=>Project Settings" and navigate to the **SOArchitecture** section as shown below.

image

image

Using the new search fields for the editor windows (in I believe 2019 and later), you can also search for the SOArchitecture library in either the **Preferences** and **Project Settings** window to make it easier to find.

image

One final related change is that I moved the SOArchitecture_Settings instance currently checked in outside of the **SO Architecture** folder so it would not be included for developers who download this as a package. Including this would potentially prevent them from modifying the contents as well 
(usually package contents are protected), but definitely prevents their settings from being overwritten when a new package version is downloaded as package contents are considered disposable when changing versions and are blown away completely during that process. Any customized settings would go away in that circumstance. Its better that this asset is created in the developers **Assets/Resources** folder initially (just how the Singleton instance creation currently works), but this would be prevented by including this asset in the package contents.

If you have any questions or concerns please let me know on the PR!

### CODE REVIEW

**Comment by jeffcampbellmakesgames** [comment]
Hey, I realize you're probably busy; just bumping this as a reminder.

**Comment by DanielEverland** [comment]
This is cool, I had no idea you could do this 👍

**Comment by DanielEverland** [comment]
I changed the feature a bit. Instead of having a pre-defined settings asset in the resources folder, the asset will generate one for you when needed. It also no longer uses the resources to locate the project settings, instead opting to query the asset database. Also added warnings if more than one settings asset is present in the project.

**Comment by DanielEverland** [comment]
Amazing PR as always, I especially appreciate the in-depth explanations :)

**Pull request merged**
