### PR TITLE
Removed developer description

### PR DESCRIPTION
**Pull request by jzapdot**
## Summary

I'm not sure if this would be useful to you, but we found after some use that we didn't like developer description as a feature because it would result in long strings being shipped with a build and rely more on the name of the SO asset to be self-documenting (or outline general usage of SO assets elsewhere). This PR removes the developer description type and adjusts its usage accordingly across the library.

Feel free to close this if not useful for you.

### CODE REVIEW

**Comment by DanielEverland** [comment]
I've thought about this myself, I never really used them when working on my own game. Seeing as they're broken in 2019.3, and I'm _way_ too busy to fix it at the moment, I think this might be a good time to say goodbye to descriptions.

You could argue that if the asset isn't understandable simply from its name, it's probably too complex, and should probably be split into multiple modules.

**Comment by DanielEverland** [comment]
Thanks for the great PR, as always :)

**Comment by jeffcampbellmakesgames** [comment]
> You could argue that if the asset isn't understandable simply from its name, it's probably too complex, and should probably be split into multiple modules.

Absolutely, totally agree with you on that end.

> Thanks for the great PR, as always :)

Glad to help!

**Comment by Monsoonexe** [comment]
I understand, but I'm sad to see this feature go.

**Pull request merged**
